{% set version = '1.1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crosstalk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crosstalk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crosstalk/crosstalk_{{ version }}.tar.gz
  sha256: 36a70b10bc11826e314c05f9579fd791b9ac3b3a2cfed4d4ca74ce1ad991300e

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-htmltools >=0.3.6
    - r-jsonlite
    - r-lazyeval
  run:
    - r-base
    - r-r6
    - r-htmltools >=0.3.6
    - r-jsonlite
    - r-lazyeval

test:
  commands:
    - $R -e "library('crosstalk')"           # [not win]
    - "\"%R%\" -e \"library('crosstalk')\""  # [win]

about:
  home: https://rstudio.github.io/crosstalk/
  license: MIT
  summary: Provides building blocks for allowing HTML widgets to communicate with each other,
    with Shiny or without (i.e. static .html files). Currently supports linked brushing
    and filtering.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: crosstalk
# Type: Package
# Title: Inter-Widget Interactivity for HTML Widgets
# Version: 1.1.0.1
# Authors@R: c( person("Joe", "Cheng", role = c("aut", "cre"), email = "joe@rstudio.com"), person(family = "RStudio", role = "cph"), person(family = "jQuery Foundation", role = "cph", comment = "jQuery library and jQuery UI library"), person(family = "jQuery contributors", role = c("ctb", "cph"), comment = "jQuery library; authors listed in inst/www/shared/jquery-AUTHORS.txt"), person("Mark", "Otto", role = "ctb", comment = "Bootstrap library"), person("Jacob", "Thornton", role = "ctb", comment = "Bootstrap library"), person(family = "Bootstrap contributors", role = "ctb", comment = "Bootstrap library"), person(family = "Twitter, Inc", role = "cph", comment = "Bootstrap library"), person("Brian", "Reavis", role = c("ctb", "cph"), comment = "selectize.js library"), person("Kristopher Michael", "Kowal", role = c("ctb", "cph"), comment = "es5-shim library"), person(family = "es5-shim contributors", role = c("ctb", "cph"), comment = "es5-shim library"), person("Denis", "Ineshin", role = c("ctb", "cph"), comment = "ion.rangeSlider library"), person("Sami", "Samhuri", role = c("ctb", "cph"), comment = "Javascript strftime library") )
# Description: Provides building blocks for allowing HTML widgets to communicate with each other, with Shiny or without (i.e. static .html files). Currently supports linked brushing and filtering.
# License: MIT + file LICENSE
# Imports: htmltools (>= 0.3.6), jsonlite, lazyeval, R6
# Suggests: shiny, ggplot2, testthat (>= 2.1.0)
# URL: https://rstudio.github.io/crosstalk/
# BugReports: https://github.com/rstudio/crosstalk/issues
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2020-03-12 23:34:05 UTC; jcheng
# Author: Joe Cheng [aut, cre], RStudio [cph], jQuery Foundation [cph] (jQuery library and jQuery UI library), jQuery contributors [ctb, cph] (jQuery library; authors listed in inst/www/shared/jquery-AUTHORS.txt), Mark Otto [ctb] (Bootstrap library), Jacob Thornton [ctb] (Bootstrap library), Bootstrap contributors [ctb] (Bootstrap library), Twitter, Inc [cph] (Bootstrap library), Brian Reavis [ctb, cph] (selectize.js library), Kristopher Michael Kowal [ctb, cph] (es5-shim library), es5-shim contributors [ctb, cph] (es5-shim library), Denis Ineshin [ctb, cph] (ion.rangeSlider library), Sami Samhuri [ctb, cph] (Javascript strftime library)
# Maintainer: Joe Cheng <joe@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-03-13 10:20:06 UTC
