{% set version = "1.1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crosstalk
  version: {{ version|replace("-", "_") }}

source:
  fn: crosstalk_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/crosstalk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crosstalk/crosstalk_{{ version }}.tar.gz
  sha256: 36a70b10bc11826e314c05f9579fd791b9ac3b3a2cfed4d4ca74ce1ad991300e

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-ggplot2
    - r-htmltools >=0.3.5
    - r-jsonlite
    - r-lazyeval
    - r-shiny >=0.11
  run:
    - r-base
    - r-r6
    - r-ggplot2
    - r-htmltools >=0.3.5
    - r-jsonlite
    - r-lazyeval
    - r-shiny >=0.11

test:
  commands:
    - $R -e "library('crosstalk')"           # [not win]
    - "\"%R%\" -e \"library('crosstalk')\""  # [win]

about:
  home: https://rstudio.github.io/crosstalk/
  license: MIT
  license_file: 
    - LICENSE.note 
    - LICENSE 

  summary: Provides building blocks for allowing HTML widgets to communicate with each other, with Shiny or without (i.e. static .html files). Currently supports
    linked brushing and filtering.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - halldc
