appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: IAu3A5+HpoS6bhLTPSUis/Wkg1FGCpI+zP5vO22HC+yITzNyy0RGEzr98ak+OwDjEaT3JOJtY4LMxNO2LOGwfjg0/uCO1MJSo26U0MKv2rPqpS8Nk5wEL5BDUSC4c5TidTu8x9bQ4DDKjMkr4DEsHhnDYmu1Wzb17j0+x41o7XGlCkRpU7iZ1BcgQgBZirhV2Yr9yNCRfHeY5lns3wGxhzR3W6LC/pbWnC9ISD38BySlWq3NBRsMk+86gCzwR6tx5MHRqb7yB8CoUjxJVeDDiWnwcps6/Qxm0WT5RE3gLCOtBDr0E+vPQohV/bOYmc3B5reJwgGT7Ql0yeM7l7a6hXJ1VOf0Wl/hLOuqaf01vH8nQ5l9Xt7xNXkqDRfBIHI4P8grGMHObp4zDE+li5SUVm+HNwDwMRA4qHHA38WYABTmAqQ2xCggW7+9El5d7Xgg0oJQvnTxcPAp99Hep48+AEXbBtV2VLE9JvqPRBhT3nRZpGVog8Ktv8gsU1XML2j5+1XZRquLHsp+XCfh2pE1o7npF4iU/YJKqVAuHhg/Cpw3sN5dtmZRu+kQEnyw0GJdWMM+/eZ1Fc0OTnBT+7HUFG/GtGBasBI7jZChvg2diexai1XoVd3V4H4JAPWfpSulKNWVaGA/NvGxDVr3Nx+31UiulH4nn5C7HoMsfWEICuo=}
